version: '3'
services:
  db:
    container_name: abz-test-task-db-dev
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DATABASE=ttdb
    volumes:
      - ./volumes/postgres-dev:/var/lib/postgresql/data
    ports:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    container_name: abz-test-task-backend
    image: denysbolshakov/abz-test-task-backend:latest
    build: 
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - 3000:3000
    restart: always
    env_file:
      - .env
    volumes:
      - ./volumes/uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy
