export const DATA_SOURCE_DI_TOKEN = 'DATA_SOURCE';

export const USER_REPOSITORY_DI_TOKEN = 'USER_REPOSITORY';
export const POSITION_REPOSITORY_DI_TOKEN = 'POSITION_REPOSITORY';
export const TOKEN_REPOSITORY_DI_TOKEN = 'TOKEN_REPOSITORY';
